name: continuous build

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        task: ["unittest_gtest", "cmake_test", "sanitizer_test", "s390x_test"]
        os: [macos-10.15, ubuntu-18.04]
        exclude:
          # excludes sanitizer_test and s390x_test on macOS
          - os: macos-10.15
            task: "sanitizer_test"
          - os: macos-10.15
            task: "s390x_test"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Miniconda
        if: ${{ matrix.task == 'cmake_test' || matrix.task == 'sanitizer_test' }}
        shell: bash -l {0}
        run: |
          if [[ "${{ matrix.os }}" == "macos-10.15" ]]; then
            wget --no-verbose -O conda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
          else
            wget --no-verbose -O conda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
          fi
          bash conda.sh -b -p $HOME/miniconda
      - name: Install Dependencies
        run: |
          if [[ $(uname) != "Darwin" ]]; then
            sudo apt update
            sudo apt install doxygen libcurl4-openssl-dev gcc-5 g++-5
          else
            brew install libomp doxygen gcc@11
          fi
          python3 -m pip install --user --upgrade pip setuptools
          python3 -m pip install --user flake8 pylint cpplint
      - name: Lint
        run: |
          TASK=lint ./scripts/test_script.sh
      - name: googletest
        shell: bash -l {0}
        run: |
          if [[ "${{ matrix.task }}" == "s390x_test" ]]; then
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          fi
          TASK=${{ matrix.task }} ./scripts/test_script.sh
